name: Arduino Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v3
        with:
          library-manager: submit
          compliance: strict
          project-type: library
